version: "3.8"

services:
  api:
    build: ./api/
    ports:
      - "3000:3000"
    depends_on:
      - redis_db
    env_file:
      - ./api/.env

  redis_db:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data