---
- name: Install and Start Docker
  hosts: all
  become: true
  tasks:
   # - name: Install yum essentials
   #   yum:
   #     name: yum-utils
   #     state: latest

    - name: Configure yum repository for docker
      yum_repository:
        name: docker
        description: 'yum repo for docker'
        baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
        state: present
        gpgcheck: true

    - name: Install Docker
      yum:
        name: docker
        state: present
        update_cache: yes

    - name: Start docker service
      service:
        name: docker
        state: started
      
