---
- name: Install and Start Docker
  hosts: all
  become: true
  tasks:
    - name: Install yum essentials
      yum:
        name: yum-utils
        state: latest
    
    - name: Configure yum repository for docker
      yum_repository:
        name: docker
        description: 'yum repo for docker'
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
        state: present
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
    
    - name: Install Docker
      yum:
        name: "{{ item }}"
        loop:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes
      
