---
- name: deploy docker container
  hosts: all
  become: true
  vars:
   img_id: "{{lookup('env', 'BUILD_NUMBER')}}"
  tasks:
    - name: pull docker image
      community.docker.docker_container:
        name: url-shortener
        image: karma792/url-shortener:{{img_id}}
        ports:
          - "5000:5000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always

    - name: deploy redis db
      community.docker.docker_container:
        name: redis_db
        image: redis:alpine
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
        restart_policy: always
